/**
 * YouTube 字幕抓取。
 *
 * 视频没有「正文」可言，字幕就是它的正文 —— 这是唯一能把视频内容喂给
 * TF-IDF / 实体抽取的途径。
 *
 * 优先人工字幕，没有才用自动字幕：自动字幕（ASR）有大量重复行和识别错误，
 * 需要额外的去重清洗。
 */

import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, readdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { config, hasYtdlp, ytdlpCommonArgs } from "@/core/env";
import { limiter, withRetry } from "@/core/limit";
import { normalizeToIso } from "@/core/dates";

const execFileAsync = promisify(execFile);

/**
 * 字幕抓取串行执行。
 *
 * 实测并发抓十几条字幕会被 YouTube 回 429 —— 因为整批请求都从同一个代理 IP
 * 出去，在对方看来就是同一来源的突发流量。串行 + 退避重试是唯一稳妥的做法；
 * 这里慢几秒远好过整批失败。
 */
const subtitleGate = limiter("ytdlp:subtitle", 1);

export interface TranscriptResult {
  text: string;
  lang?: string;
  autoGenerated: boolean;
  error?: string;
  /**
   * 视频的发布日期。搜索阶段的 `--flat-playlist` 拿不到它（YouTube 的搜索
   * JSON 里没有这个字段），但抓字幕时本来就要对单个视频跑一次 yt-dlp，
   * 用 `--write-info-json` 顺手写出来即可，零额外请求。
   *
   * 拿不到就是 `undefined` —— 不拿抓取时间顶替。
   *
   * 声量指标**不**从这里出去：它们是搜索层的排序依据，而搜索层已经从
   * `--flat-playlist` 拿到了播放量。再开一条 `Document.signals` 通道只会让
   * UI 需要判断「该读哪个」，收益却只是多出点赞/评论两个没人用来排序的数。
   */
  publishedAt?: string;
}

/** 从各种 YouTube URL 形态里取视频 ID。 */
export function youtubeId(url: string): string | null {
  try {
    const u = new URL(url);
    if (u.hostname === "youtu.be") return u.pathname.slice(1) || null;
    if (!u.hostname.endsWith("youtube.com")) return null;
    if (u.pathname === "/watch") return u.searchParams.get("v");
    const m = u.pathname.match(/^\/(?:embed|shorts|v)\/([^/]+)/);
    return m?.[1] ?? null;
  } catch {
    return null;
  }
}

export function isYoutubeUrl(url: string): boolean {
  return youtubeId(url) !== null;
}

export async function fetchTranscript(
  url: string,
  opts: { signal?: AbortSignal } = {},
): Promise<TranscriptResult> {
  if (!(await hasYtdlp())) {
    return {
      text: "",
      autoGenerated: false,
      error: "未安装 yt-dlp，无法获取字幕。安装：uv tool install yt-dlp",
    };
  }

  const id = youtubeId(url);
  if (!id) return { text: "", autoGenerated: false, error: "无法解析视频 ID" };

  const dir = await mkdtemp(path.join(tmpdir(), "muti-eye-sub-"));

  try {
    // 先试人工字幕，再用自动字幕兜底。--sub-langs 用 zh.* / en.* 覆盖 zh-Hans、
    // zh-CN、en-US 这些变体，否则会因语言标签不精确而漏掉。
    const baseArgs = [
      // 这个函数只服务 YouTube，一定走代理
      ...ytdlpCommonArgs(url),
      "--skip-download",
      /*
        顺手把元信息写成 JSON。

        这是补上 YouTube 日期缺口的关键一步，而且**不花任何额外请求**：
        yt-dlp 为了拿字幕本来就要完整抽取一次这个视频，`--write-info-json`
        只是把已经解析出来的 info dict 落盘。搜索阶段的 `--flat-playlist`
        给不出 upload_date（实测字段是 null），所以日期只能在这里补。

        不用 `--print` 是因为它隐含 `--simulate`，而 `--simulate` 会
        **不写任何文件** —— 那会连带把字幕写盘也一起废掉。`--write-info-json`
        与 `--write-sub` 是并列的后处理步骤，互不干扰。
      */
      "--write-info-json",
      "--convert-subs",
      "vtt",
      "--sub-langs",
      "zh-Hans,zh-CN,zh,en,en-US,en-GB",
      "-o",
      path.join(dir, "%(id)s"),
    ];

    let autoGenerated = false;
    let lastError: string | undefined;

    for (const mode of ["--write-sub", "--write-auto-sub"] as const) {
      try {
        await subtitleGate(() =>
          withRetry(() =>
            execFileAsync(
              config.ytdlpPath,
              [mode, ...baseArgs, url],
              { timeout: 90_000, signal: opts.signal, maxBuffer: 8 * 1024 * 1024 },
            ),
          ),
        );
        autoGenerated = mode === "--write-auto-sub";
        const files = await readdir(dir);
        if (files.some((f) => f.endsWith(".vtt"))) break;
      } catch (err) {
        lastError = err instanceof Error ? err.message : String(err);
      }
    }

    const files = await readdir(dir);
    const meta = await readInfoJson(dir, files);

    const vttFile = files.find((f) => f.endsWith(".vtt"));
    if (!vttFile) {
      return {
        text: "",
        autoGenerated,
        // 没有字幕也是有价值的：至少拿到了发布日期和播放量，兜底文档
        // 因此能带上时间进语料，而不是一条什么都没有的记录
        ...meta,
        error: lastError ?? "该视频没有可用字幕",
      };
    }

    const raw = await readFile(path.join(dir, vttFile), "utf8");
    const langMatch = vttFile.match(/\.([a-zA-Z-]+)\.vtt$/);
    const text = parseVtt(raw, autoGenerated);

    if (!text.trim()) {
      return { text: "", autoGenerated, ...meta, error: "字幕文件为空" };
    }

    return { text, lang: langMatch?.[1], autoGenerated, ...meta };
  } catch (err) {
    return {
      text: "",
      autoGenerated: false,
      error: err instanceof Error ? err.message : String(err),
    };
  } finally {
    await rm(dir, { recursive: true, force: true }).catch(() => {});
  }
}

/**
 * 解析 WebVTT。
 *
 * 自动字幕（ASR）有两个必须处理的毛病：
 *  1. 滚动式显示 —— 同一句话会以逐步增多的前缀重复出现多次
 *  2. 行内带有 <00:00:00.000><c> 之类的标记
 * 不去重的话，一段 10 分钟视频能产出几万字的重复文本，直接把 TF-IDF 带偏。
 */
/**
 * 读 `--write-info-json` 落下的元信息，取出发布日期与声量指标。
 *
 * 整个函数是**尽力而为**的：文件不在、JSON 坏了、字段缺了，都只是少一个字段，
 * 绝不让它影响字幕那条主路径。这不是「错误处理走过场」—— 元信息本来就是
 * 顺带的，为它把一次成功的字幕抓取判成失败是本末倒置。
 */
async function readInfoJson(
  dir: string,
  files: string[],
): Promise<{ publishedAt?: string }> {
  const infoFile = files.find((f) => f.endsWith(".info.json"));
  if (!infoFile) return {};

  try {
    const info = JSON.parse(await readFile(path.join(dir, infoFile), "utf8")) as {
      upload_date?: string | null;
    };
    return { publishedAt: normalizeToIso(info.upload_date) };
  } catch {
    return {};
  }
}

export function parseVtt(raw: string, dedupe = true): string {
  const lines = raw.split(/\r?\n/);
  const cues: string[] = [];
  const seen = new Set<string>();

  for (const line of lines) {
    const t = line.trim();
    if (!t) continue;
    if (t === "WEBVTT" || t.startsWith("WEBVTT")) continue;
    if (t.startsWith("NOTE") || t.startsWith("STYLE") || t.startsWith("REGION")) continue;
    // yt-dlp 转换出的 VTT 头部，例如 "Kind: captions Language: en-US"
    if (t.startsWith("Kind:") || t.startsWith("Language:")) continue;
    // 时间轴行
    if (t.includes("-->")) continue;
    // 纯序号行
    if (/^\d+$/.test(t)) continue;

    const clean = t
      // 内联时间戳标记 <00:00:00.000>
      .replace(/<\d{2}:\d{2}:\d{2}\.\d{3}>/g, "")
      // 样式标签 <c> </c> <v Speaker> 等
      .replace(/<\/?[cvbius][^>]*>/g, "")
      .replace(/&nbsp;/g, " ")
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/\s+/g, " ")
      .trim();

    if (!clean) continue;

    if (dedupe) {
      // 完全重复的行直接丢
      if (seen.has(clean)) continue;
      seen.add(clean);
      // 滚动字幕：新行以已有的某行开头（前缀延展），说明是同一句的重复呈现
      const prev = cues.at(-1);
      if (prev && clean.startsWith(prev)) {
        cues[cues.length - 1] = clean;
        continue;
      }
      if (prev && prev.startsWith(clean)) continue;
    }

    cues.push(clean);
  }

  // 合并成连续文本。中文不用空格分隔，这里按标点断句即可。
  return cues.join(" ").replace(/\s+/g, " ").trim();
}
